# Adapted from Garnet

name: constraints

commands:
  - python gen_constraints.py

outputs:
  - constraints.tcl

parameters:

  # Name of the design
  design_name: undefined

  # Name of the ADK
  adk_name: tsmc16

  # Period of the main clock in nanoseconds
  # (will be scaled by constr_time_scale)
  constr_main_per: 0.7

  # Scale factor for timing constraints
  constr_time_scale: 1.0

  # Scale factor for capacitance constraints
  constr_cap_scale: 1.0
