# Adapted from Garnet

name: constraints

commands:
  - python gen_constraints.py

outputs:
  - constraints.tcl

parameters:
  # time in ns and capacitance in pF

  # Name of the design
  design_name: undefined

  # Scale factor for timing constraints
  constr_time_scale: 1.0

  # Scale factor for capacitance constraints
  constr_cap_scale: 1.0
