# define variables used by mLingua Makefile
TOP_MODULE := test
TIME_SCALE := 1fs/1fs	# time scale (change the value as you wish)

# source mLingua Makefile
include ../generic/generic.mk

clean::
	rm -f custom.f
