# Adapted from Garnet and ButterPHY

name: analog_core

commands:
  - |
    mkdir -p outputs
    tar -xvf /home/sjkim85/dragonphy_tarballs/analog_core-latest.tar.gz -C outputs
    mv outputs/analog_core-0.6.0/* outputs/

outputs:
  - analog_core.lef
  - analog_core.gds
  - analog_core.spi
  - analog_core.version
