

#set ip_lef [list ${aprDir}/pnr_dragonphy/data/lef/phase_interpolator.lef ${aprDir}/pnr_dragonphy/data/lef/phase_interpolator_antenna.lef ${aprDir}/pnr_dragonphy/data/lef/stochastic_adc_PR.lef ${aprDir}/pnr_dragonphy/data/lef/stochastic_adc_PR_antenna.lef ${aprDir}/pnr_dragonphy/data/lef/biasgen.lef ${aprDir}/pnr_dragonphy/data/lef/biasgen_antenna.lef ${aprDir}/pnr_dragonphy/data/analog_macro/termination/termination_exported.lef ${aprDir}/pnr_dragonphy/data/lef/input_divider.lef ${aprDir}/pnr_dragonphy/data/lef/input_divider_antenna.lef  ${aprDir}/pnr_dragonphy/data/analog_macro/SW/SW_exported.lef ${aprDir}/pnr_dragonphy/data/analog_macro/CS_cell/CS_cell_exported.lef ]
#set ip_gds [list ${aprDir}/pnr_dragonphy/data/gds/phase_interpolator_exported.gds ${aprDir}/pnr_dragonphy/data/gds/stochastic_adc_PR_exported.gds  ${aprDir}/pnr_dragonphy/data/gds/biasgen_exported.gds ${aprDir}/pnr_dragonphy/data/analog_macro/termination/termination_exported.gds ${aprDir}/pnr_dragonphy/data/gds/input_divider.gds  ${aprDir}/pnr_dragonphy/data/analog_macro/SW/SW_exported.gds]

set ip_lef [list ${aprDir}/pnr_dragonphy/phase_interpolator/results/phase_interpolator.lef ${aprDir}/pnr_dragonphy/phase_interpolator/results/phase_interpolator_Model/library/phase_interpolator_antenna.lef ${aprDir}/pnr_dragonphy/stochastic_adc_PR/results/stochastic_adc_PR.lef ${aprDir}/pnr_dragonphy/stochastic_adc_PR/results/stochastic_adc_PR_Model/library/stochastic_adc_PR_antenna.lef ${aprDir}/pnr_dragonphy/biasgen/results/biasgen.lef ${aprDir}/pnr_dragonphy/biasgen/results/biasgen_Model/library/biasgen_antenna.lef  ${aprDir}/pnr_dragonphy/input_divider/results/input_divider.lef ${aprDir}/pnr_dragonphy/input_divider/results/input_divider_Model/library/input_divider_antenna.lef ${aprDir}/pnr_dragonphy/data/analog_macro/termination/termination_exported.lef ${aprDir}/pnr_dragonphy/data/analog_macro/SW/SW_exported.lef ${aprDir}/pnr_dragonphy/data/analog_macro/CS_cell/CS_cell_exported.lef ${aprDir}/pnr_dragonphy/new_adc/results/new_adc.lef ${aprDir}/pnr_dragonphy/new_adc/results/new_adc_Model/library/new_adc_antenna.lef]

set ip_gds [list ${aprDir}/pnr_dragonphy/phase_interpolator/results/phase_interpolator_exported.gds ${aprDir}/pnr_dragonphy/stochastic_adc_PR/results/stochastic_adc_PR_exported.gds  ${aprDir}/pnr_dragonphy/biasgen/results/biasgen_exported.gds ${aprDir}/pnr_dragonphy/input_divider/results/input_divider.gds ${aprDir}/pnr_dragonphy/data/analog_macro/termination/termination_exported.gds ${aprDir}/pnr_dragonphy/data/analog_macro/SW/SW_exported.gds  ${aprDir}/pnr_dragonphy/new_adc/results/new_adc_exported.gds]




