

set file [open TDC_in_net.txt w]
puts $file "pfd_out"
close $file



deleteBufferTree -selNetFile TDC_in_net.txt

set_ccopt_property opt_ignore true -clock_tree clk 
set_ccopt_property opt_ignore true -clock_tree clk_adc 
set_ccopt_property opt_ignore true -clock_tree clk_TDC 
set_ccopt_property opt_ignore true -clock_tree clk_async 
set_ccopt_property opt_ignore true -clock_tree clk_pm 

set_ccopt_property sink_type stop -pin idchain/iTDC_delay_unit_dont_touch_*_/ff_out_reg/D


create_ccopt_clock_tree -name data_tree_TDC_in -source iPFD/U5/Z -no_skew_group
create_ccopt_skew_group -name sg_data_tree_TDC_in -source iPFD/U5/Z  -sink idchain/iTDC_delay_unit_dont_touch_0_/ff_out_reg/D
get_ccopt_property -skew_group sg_data_tree_TDC_in sinks_active


set_ccopt_property target_skew 0.01 -skew sg_data_tree_TDC_in
set_ccopt_property target_max_trans 0.03 -clock_tree data_tree_TDC_in

set_ccopt_property update_io_latency false
set_ccopt_property post_conditioning false
set_ccopt_property use_estimated_routes_during_final_implementation true

 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_1_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_2_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_3_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_4_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_5_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_6_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_7_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_8_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_9_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_10_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_11_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_12_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_13_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_14_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_15_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_16_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_17_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_18_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_19_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_20_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_21_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_22_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_23_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_24_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_25_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_26_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_27_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_28_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_29_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_30_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_31_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_32_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_33_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_34_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_35_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_36_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_37_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_38_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_39_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_40_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_41_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_42_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_43_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_44_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_45_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_46_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_47_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_48_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_49_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_50_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_51_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_52_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_53_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_54_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_55_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_56_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_57_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_58_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_59_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_60_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_61_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_62_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_63_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_64_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_65_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_66_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_67_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_68_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_69_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_70_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_71_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_72_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_73_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_74_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_75_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_76_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_77_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_78_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_79_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_80_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_81_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_82_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_83_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_84_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_85_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_86_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_87_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_88_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_89_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_90_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_91_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_92_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_93_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_94_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_95_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_96_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_97_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_98_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_99_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_100_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_101_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_102_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_103_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_104_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_105_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_106_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_107_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_108_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_109_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_110_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_111_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_112_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_113_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_114_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_115_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_116_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_117_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_118_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_119_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_120_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_121_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_122_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_123_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_124_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_125_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_126_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_127_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_128_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_129_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_130_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_131_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_132_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_133_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_134_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_135_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_136_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_137_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_138_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_139_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_140_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_141_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_142_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_143_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_144_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_145_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_146_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_147_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_148_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_149_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_150_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_151_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_152_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_153_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_154_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_155_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_156_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_157_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_158_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_159_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_160_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_161_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_162_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_163_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_164_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_165_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_166_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_167_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_168_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_169_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_170_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_171_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_172_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_173_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_174_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_175_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_176_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_177_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_178_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_179_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_180_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_181_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_182_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_183_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_184_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_185_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_186_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_187_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_188_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_189_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_190_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_191_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_192_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_193_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_194_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_195_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_196_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_197_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_198_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_199_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_200_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_201_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_202_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_203_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_204_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_205_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_206_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_207_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_208_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_209_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_210_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_211_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_212_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_213_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_214_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_215_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_216_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_217_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_218_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_219_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_220_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_221_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_222_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_223_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_224_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_225_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_226_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_227_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_228_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_229_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_230_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_231_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_232_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_233_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_234_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_235_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_236_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_237_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_238_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_239_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_240_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_241_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_242_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_243_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_244_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_245_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_246_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_247_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_248_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_249_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_250_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_251_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_252_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_253_/ff_out_reg/D
 modify_ccopt_skew_group -skew_group sg_data_tree_TDC_in -add_sinks idchain/iTDC_delay_unit_dont_touch_254_/ff_out_reg/D

ccopt_design -cts






