steps:
  - command: |
      # set up environment
      source /cad/modules/tcl/init/bash
      module load base xcelium
      export DRAGONPHY_PYTHON=/usr/local/miniconda/bin/python3.7
      export DW_TAP=/cad/synopsys/syn/L-2016.03-SP5-5/dw/sim_ver/DW_tap.v
      export BUILD_VIEW=cpu
      printenv

      # run regression script
      source regress.sh
    label: "test"
    timeout_in_minutes: 60
    agents:
      fault2: "true"
  - command: |
      # set up environment
      source /etc/environment
      export DRAGONPHY_PYTHON=python3.7
      export FPGA_SERVER=1
      export DW_TAP=/tools/synopsys/syn/L-2016.03-SP5-5/dw/sim_ver/DW_tap.v
      export BUILD_VIEW=fpga
      printenv

      # run regression script
      source regress.sh
    label: "test_emu"
    timeout_in_minutes: 60
    agents:
        fpga_verif: "true"
