steps:
  - command: |
      source /cad/modules/tcl/init/bash
      module load base
      module load xcelium
      conda create -p ./conda_env -m -y pip python=3.7.4
      export PATH="${PWD}/conda_env/bin:${PATH}"
      pip install -e .
      pip install pytest
      pytest tests
    label: "sim-test"

  - command: |
      export PATH="/home/steven/miniconda3/bin:${PATH}"
      conda create -p ./conda_env -m -y pip python=3.7.4
      export PATH="${PWD}/conda_env/bin:${PATH}"
      pip install -e .
      pip install pytest
      cd emu
      ./build.sh
      pytest
    label: "fpga-test"
    agents:
      fpga-test: "true"
