steps:
  - command: |
      # set up environment
      export PATH=$$PATH:/usr/local/miniconda/bin:/usr/local/bin
      echo $$PATH
      export LD_LIBRARY_PATH=$$LD_LIBRARY_PATH:/usr/local/lib
      echo $$LD_LIBRARY_PATH

      # tool setup
      source /cad/modules/tcl/init/bash
      module load base xcelium

      # create conda env
      conda create -p ./conda_env -m -y pip python=3.7.4
      export PATH=$$PWD/conda_env/bin:$$PATH

      # install dragonphy
      pip install -e .

      # run tests
      pip install pytest
      pytest tests -xs
    label: "test"
    timeout_in_minutes: 60
    agents:
      butterphy: "true"
  - command: |
      # set up environment
      source /etc/environment
      echo $$PATH

      # activate virtual env
      python3.7 -m venv venv
      source venv/bin/activate

      # install dragonphy
      pip install -e .

      # install pytest to allow tests to run
      pip install pytest

      # build bitstream
      pytest emu/test_emu_build.py -xs

      # show results of bitstream build
      tree emu
      cat emu/project/project.runs/synth_1/runme.log
      cat emu/project/project.runs/impl_1/runme.log

      # program FPGA and run test
      pytest emu/test_emu_prog.py -xs

      # deactivate virtual env
      deactivate
    label: "test_emu"
    timeout_in_minutes: 60
    agents:
        fpga_verif: "true"
