steps:
  - command: |
      source /cad/modules/tcl/init/bash
      module load base
      module load xcelium
      conda create -p ./conda_env -m -y pip python=3.7.4
      export PATH=$PWD/conda_env/bin:$PATH
      pip install -e .
      pip install pytest
      pytest tests
    label: "test"
    agents:
      butterphy: "true"
  - command: |
      python3.7 -m venv venv
      source venv/bin/activate
      pip install pytest
      pip install -e .
      pytest emu/test_emu_build.py
      deactivate
    label: "test_emu"
    agents:
        fpga_verif: "true"
