# Adapted from Garnet and ButterPHY

name: input_divider

commands:
  - |
    mkdir -p outputs
    tar -xvf /home/sjkim85/dragonphy_tarballs/input_divider-latest.tar.gz -C outputs
    mv outputs/input_divider-0.1.0/* outputs/
outputs:
  - input_divider.lef
  - input_divider.gds
  - input_divider.spi
  - input_divider.version
