//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11879 $ --- $Date: 2013/06/11 $   |
//	-----------------------------------------------
//	
//
//  Source file: /sim/zamyers/JusTAG/rtl/primitives/cfg_ifc.svp
//  Source template: cfg_ifc
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
// Parameter DataWidth 	= 32
// Parameter AddrWidth 	= 14
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

/*************************************************************************
 ** From Perforce:
 **
 ** $Id: //Smart_design/ChipGen/rtl/Primitives/cfg_ifc.vp#1 $
 ** $DateTime: 2010/05/07 23:11:33 $
 ** $Change: 8691 $
 ** $Author: shacham $
 *************************************************************************/

/* *****************************************************************************
 * File: cfg_ifc.vp
 * 
 * Description:
 * Interface definitions and parametrization for the cfg_ifc primitive
 * 
 * REQUIRED GENESIS PARAMETERS:
 * ----------------------------
 * * DataWidth - width of the configuration bus (default is 32bit)
 * * AddrWidth - width of the configuration bus address (default is 32bit)
 * * OpcodeWidth - width of the configuration bus opcode (default is 2bit)
 * 
 * 
 * Inputs:
 * -------
 * cfgIn.addr - input address for config transaction
 * cfgIn.data - input data for config transaction
 * cfgIn.op -  nop/write/read/bypass enabler for the address specified on cfgIn.addr 
 *		and the data specified by cfgIn.data
 * 
 * 
 * Outputs:
 * --------
 * cfgOut.addr - output address for config transaction
 * cfgOut.data - output data for config transaction
 * cfgOut.op - output config opcode (for multi module concatenation)
 * 
 * 
 * Change bar:
 * -----------
 * Date          Author   Description
 * May  3, 2010  shacham  init version
 * Apr 18, 2012  shacham  clean up of names and genesis syntactic sugar
 * 
 * 
 * ****************************************************************************/

// ACTUAL GENESIS2 PARAMETERIZATIONS
// DataWidth (_GENESIS2_INHERITANCE_PRIORITY_) = 32
//
// AddrWidth (_GENESIS2_INHERITANCE_PRIORITY_) = 14
//
// OpcodeWidth (_GENESIS2_DECLARATION_PRIORITY_) = 2
//

interface cfg_ifc_unq1();
   logic [13:0] addr;
   logic [31:0]  data;
   logic [1:0] 	 op;
   
   modport cfgIn(//messages arriving from prev cfg node
    input 			 addr,
    input 			 data,
    input 			 op 			 
		   );

   modport cfgOut(// messages sent to next cfg node
    output 			 addr,
    output 			 data,
    output 			 op 			 
		   );
endinterface: cfg_ifc_unq1
