//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11879 $ --- $Date: 2013/06/11 $   |
//	-----------------------------------------------
//	
//
//  Source file: /sim/zamyers/JusTAG/rtl/digital/raw_jtag_ifc.svp
//  Source template: raw_jtag_ifc
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
// Parameter IOList 	= Data structure of type ARRAY
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

// IOList (_GENESIS2_INHERITANCE_PRIORITY_) = 
//	[ { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_v2t, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>16, bsr=>yes, direction=>out, name=>en_slice, orientation=>top, signed=>0 },
//	  { array=>16, bitwidth=>5, bsr=>yes, direction=>out, name=>ctl_v2tn, orientation=>top, signed=>0 },
//	  { array=>16, bitwidth=>5, bsr=>yes, direction=>out, name=>ctl_v2tp, orientation=>top, signed=>0 },
//	  { array=>16, bitwidth=>2, bsr=>yes, direction=>out, name=>init, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>16, bsr=>yes, direction=>out, name=>ALWS_ON, orientation=>top, signed=>0 },
//	  { array=>16, bitwidth=>2, bsr=>yes, direction=>out, name=>sel_pm_sign, orientation=>top, signed=>0 },
//	  { array=>16, bitwidth=>2, bsr=>yes, direction=>out, name=>sel_pm_in, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>16, bsr=>yes, direction=>out, name=>sel_clk_TDC, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>16, bsr=>yes, direction=>out, name=>en_pm, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>16, bsr=>yes, direction=>out, name=>en_v2t_clk_next, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>16, bsr=>yes, direction=>out, name=>en_sw_test, orientation=>top, signed=>0 },
//	  { array=>16, bitwidth=>2, bsr=>yes, direction=>out, name=>ctl_dcdl_late, orientation=>top, signed=>0 },
//	  { array=>16, bitwidth=>2, bsr=>yes, direction=>out, name=>ctl_dcdl_early, orientation=>top, signed=>0 },
//	  { array=>16, bitwidth=>5, bsr=>yes, direction=>out, name=>ctl_dcdl_TDC, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_gf, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>en_arb_pi, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>en_delay_pi, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>en_ext_Qperi, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>en_pm_pi, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>en_cal_pi, orientation=>top, signed=>0 },
//	  { array=>4, bitwidth=>5, bsr=>yes, direction=>out, name=>ext_Qperi, orientation=>top, signed=>0 },
//	  { array=>4, bitwidth=>2, bsr=>yes, direction=>out, name=>sel_pm_sign_pi, orientation=>top, signed=>0 },
//	  { array=>4, bitwidth=>32, bsr=>yes, direction=>out, name=>del_inc, orientation=>top, signed=>0 },
//	  { array=>4, bitwidth=>2, bsr=>yes, direction=>out, name=>ctl_dcdl_slice, orientation=>top, signed=>0 },
//	  { array=>4, bitwidth=>2, bsr=>yes, direction=>out, name=>ctl_dcdl_sw, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>disable_state, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>en_clk_sw, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>en_meas_pi, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>sel_meas_pi, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>2, bsr=>yes, direction=>out, name=>en_slice_rep, orientation=>top, signed=>0 },
//	  { array=>2, bitwidth=>5, bsr=>yes, direction=>out, name=>ctl_v2tn_rep, orientation=>top, signed=>0 },
//	  { array=>2, bitwidth=>5, bsr=>yes, direction=>out, name=>ctl_v2tp_rep, orientation=>top, signed=>0 },
//	  { array=>2, bitwidth=>2, bsr=>yes, direction=>out, name=>init_rep, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>2, bsr=>yes, direction=>out, name=>ALWS_ON_rep, orientation=>top, signed=>0 },
//	  { array=>2, bitwidth=>2, bsr=>yes, direction=>out, name=>sel_pm_sign_rep, orientation=>top, signed=>0 },
//	  { array=>2, bitwidth=>2, bsr=>yes, direction=>out, name=>sel_pm_in_rep, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>2, bsr=>yes, direction=>out, name=>sel_clk_TDC_rep, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>2, bsr=>yes, direction=>out, name=>en_pm_rep, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>2, bsr=>yes, direction=>out, name=>en_v2t_clk_next_rep, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>2, bsr=>yes, direction=>out, name=>en_sw_test_rep, orientation=>top, signed=>0 },
//	  { array=>2, bitwidth=>2, bsr=>yes, direction=>out, name=>ctl_dcdl_late_rep, orientation=>top, signed=>0 },
//	  { array=>2, bitwidth=>2, bsr=>yes, direction=>out, name=>ctl_dcdl_early_rep, orientation=>top, signed=>0 },
//	  { array=>2, bitwidth=>5, bsr=>yes, direction=>out, name=>ctl_dcdl_TDC_rep, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>sel_pfd_in, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>sel_pfd_in_meas, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_pfd_inp_meas, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_pfd_inn_meas, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>sel_del_out, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>disable_ibuf_async, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>disable_ibuf_aux, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>disable_ibuf_test0, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>disable_ibuf_test1, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_inbuf, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>sel_inbuf_in, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>bypass_inbuf_div, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>3, bsr=>yes, direction=>out, name=>inbuf_ndiv, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_inbuf_meas, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>en_biasgen, orientation=>top, signed=>0 },
//	  { array=>4, bitwidth=>4, bsr=>yes, direction=>out, name=>ctl_biasgen, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>sel_del_out_pi, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_del_out_pi, orientation=>top, signed=>0 },
//	  { array=>16, bitwidth=>20, bsr=>yes, direction=>in, name=>pm_out, orientation=>top, signed=>0 },
//	  { array=>4, bitwidth=>20, bsr=>yes, direction=>in, name=>pm_out_pi, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>in, name=>cal_out_pi, orientation=>top, signed=>0 },
//	  { array=>4, bitwidth=>5, bsr=>yes, direction=>in, name=>Qperi, orientation=>top, signed=>0 },
//	  { array=>4, bitwidth=>5, bsr=>yes, direction=>in, name=>max_sel_mux, orientation=>top, signed=>0 },
//	  { array=>2, bitwidth=>20, bsr=>yes, direction=>in, name=>pm_out_rep, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>8, bsr=>yes, direction=>out, name=>pd_offset_ext, orientation=>top, signed=>1 },
//	  { array=>1, bitwidth=>22, bsr=>yes, direction=>out, name=>i_val, orientation=>top, signed=>1 },
//	  { array=>1, bitwidth=>22, bsr=>yes, direction=>out, name=>p_val, orientation=>top, signed=>1 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_ext_pi_ctl_cdr, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>9, bsr=>yes, direction=>out, name=>ext_pi_ctl_cdr, orientation=>top, signed=>0 },
//	  { array=>4, bitwidth=>9, bsr=>yes, direction=>out, name=>ext_pi_ctl_offset, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_ext_pfd_offset, orientation=>top, signed=>0 },
//	  { array=>16, bitwidth=>8, bsr=>yes, direction=>out, name=>ext_pfd_offset, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_ext_pfd_offset_rep, orientation=>top, signed=>0 },
//	  { array=>2, bitwidth=>8, bsr=>yes, direction=>out, name=>ext_pfd_offset_rep, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_ext_max_sel_mux, orientation=>top, signed=>0 },
//	  { array=>4, bitwidth=>5, bsr=>yes, direction=>out, name=>ext_max_sel_mux, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_pfd_cal, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_pfd_cal_rep, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>Navg_adc, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>Nbin_adc, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>DZ_hist_adc, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>Navg_adc_rep, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>Nbin_adc_rep, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>DZ_hist_adc_rep, orientation=>top, signed=>0 },
//	  { array=>16, bitwidth=>8, bsr=>yes, direction=>in, name=>adcout_avg, orientation=>top, signed=>1 },
//	  { array=>16, bitwidth=>24, bsr=>yes, direction=>in, name=>adcout_sum, orientation=>top, signed=>1 },
//	  { array=>16, bitwidth=>16, bsr=>yes, direction=>in, name=>adcout_hist_center, orientation=>top, signed=>0 },
//	  { array=>16, bitwidth=>16, bsr=>yes, direction=>in, name=>adcout_hist_side, orientation=>top, signed=>0 },
//	  { array=>16, bitwidth=>8, bsr=>yes, direction=>in, name=>pfd_offset, orientation=>top, signed=>1 },
//	  { array=>2, bitwidth=>8, bsr=>yes, direction=>in, name=>adcout_avg_rep, orientation=>top, signed=>1 },
//	  { array=>2, bitwidth=>24, bsr=>yes, direction=>in, name=>adcout_sum_rep, orientation=>top, signed=>1 },
//	  { array=>2, bitwidth=>16, bsr=>yes, direction=>in, name=>adcout_hist_center_rep, orientation=>top, signed=>0 },
//	  { array=>2, bitwidth=>16, bsr=>yes, direction=>in, name=>adcout_hist_side_rep, orientation=>top, signed=>0 },
//	  { array=>2, bitwidth=>8, bsr=>yes, direction=>in, name=>pfd_offset_rep, orientation=>top, signed=>1 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>Ndiv_clk_avg, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>Ndiv_clk_cdr, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>int_rstb, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>sram_rstb, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>cdr_rstb, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>sel_outbuff, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>4, bsr=>yes, direction=>out, name=>sel_trigbuff, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_outbuff, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>en_trigbuff, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>3, bsr=>yes, direction=>out, name=>Ndiv_outbuff, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>3, bsr=>yes, direction=>out, name=>Ndiv_trigbuff, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>bypass_out, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>1, bsr=>yes, direction=>out, name=>bypass_trig, orientation=>top, signed=>0 },
//	  { array=>1, bitwidth=>10, bsr=>yes, direction=>out, name=>in_addr, orientation=>top, signed=>0 },
//	  { array=>18, bitwidth=>8, bsr=>yes, direction=>in, name=>out_data, orientation=>top, signed=>1 },
//	  { array=>1, bitwidth=>10, bsr=>yes, direction=>in, name=>addr, orientation=>top, signed=>0 },
//	  { bitwidth=>1, bsr=>no, direction=>in, name=>tck, orientation=>right, pad=>digital },
//	  { bitwidth=>1, bsr=>no, direction=>in, name=>trst_n, orientation=>right, pad=>digital },
//	  { bitwidth=>1, bsr=>no, direction=>in, name=>tms, orientation=>right, pad=>digital },
//	  { bitwidth=>1, bsr=>no, direction=>in, name=>tdi, orientation=>right, pad=>digital },
//	  { bitwidth=>1, bsr=>no, direction=>out, name=>tdo, orientation=>right, pad=>digital },
//	  { bitwidth=>1, bsr=>no, direction=>out, name=>tdo_en, orientation=>right, pad=>digital }
//	]
//
// Constants (_GENESIS2_DECLARATION_PRIORITY_) = 
//
interface raw_jtag_ifc_unq1(input wire Clk, input wire Reset);
    logic   en_v2t; 
    logic  [15:0] en_slice; 
    logic  [4:0] ctl_v2tn[15:0]; 
    logic  [4:0] ctl_v2tp[15:0]; 
    logic  [1:0] init[15:0]; 
    logic  [15:0] ALWS_ON; 
    logic  [1:0] sel_pm_sign[15:0]; 
    logic  [1:0] sel_pm_in[15:0]; 
    logic  [15:0] sel_clk_TDC; 
    logic  [15:0] en_pm; 
    logic  [15:0] en_v2t_clk_next; 
    logic  [15:0] en_sw_test; 
    logic  [1:0] ctl_dcdl_late[15:0]; 
    logic  [1:0] ctl_dcdl_early[15:0]; 
    logic  [4:0] ctl_dcdl_TDC[15:0]; 
    logic   en_gf; 
    logic  [3:0] en_arb_pi; 
    logic  [3:0] en_delay_pi; 
    logic  [3:0] en_ext_Qperi; 
    logic  [3:0] en_pm_pi; 
    logic  [3:0] en_cal_pi; 
    logic  [4:0] ext_Qperi[3:0]; 
    logic  [1:0] sel_pm_sign_pi[3:0]; 
    logic  [31:0] del_inc[3:0]; 
    logic  [1:0] ctl_dcdl_slice[3:0]; 
    logic  [1:0] ctl_dcdl_sw[3:0]; 
    logic  [3:0] disable_state; 
    logic  [3:0] en_clk_sw; 
    logic  [3:0] en_meas_pi; 
    logic  [3:0] sel_meas_pi; 
    logic  [1:0] en_slice_rep; 
    logic  [4:0] ctl_v2tn_rep[1:0]; 
    logic  [4:0] ctl_v2tp_rep[1:0]; 
    logic  [1:0] init_rep[1:0]; 
    logic  [1:0] ALWS_ON_rep; 
    logic  [1:0] sel_pm_sign_rep[1:0]; 
    logic  [1:0] sel_pm_in_rep[1:0]; 
    logic  [1:0] sel_clk_TDC_rep; 
    logic  [1:0] en_pm_rep; 
    logic  [1:0] en_v2t_clk_next_rep; 
    logic  [1:0] en_sw_test_rep; 
    logic  [1:0] ctl_dcdl_late_rep[1:0]; 
    logic  [1:0] ctl_dcdl_early_rep[1:0]; 
    logic  [4:0] ctl_dcdl_TDC_rep[1:0]; 
    logic   sel_pfd_in; 
    logic   sel_pfd_in_meas; 
    logic   en_pfd_inp_meas; 
    logic   en_pfd_inn_meas; 
    logic   sel_del_out; 
    logic   disable_ibuf_async; 
    logic   disable_ibuf_aux; 
    logic   disable_ibuf_test0; 
    logic   disable_ibuf_test1; 
    logic   en_inbuf; 
    logic   sel_inbuf_in; 
    logic   bypass_inbuf_div; 
    logic  [2:0] inbuf_ndiv; 
    logic   en_inbuf_meas; 
    logic  [3:0] en_biasgen; 
    logic  [3:0] ctl_biasgen[3:0]; 
    logic   sel_del_out_pi; 
    logic   en_del_out_pi; 
    logic  [19:0] pm_out[15:0]; 
    logic  [19:0] pm_out_pi[3:0]; 
    logic  [3:0] cal_out_pi; 
    logic  [4:0] Qperi[3:0]; 
    logic  [4:0] max_sel_mux[3:0]; 
    logic  [19:0] pm_out_rep[1:0]; 
    logic signed [7:0] pd_offset_ext; 
    logic signed [21:0] i_val; 
    logic signed [21:0] p_val; 
    logic   en_ext_pi_ctl_cdr; 
    logic  [8:0] ext_pi_ctl_cdr; 
    logic  [8:0] ext_pi_ctl_offset[3:0]; 
    logic   en_ext_pfd_offset; 
    logic  [7:0] ext_pfd_offset[15:0]; 
    logic   en_ext_pfd_offset_rep; 
    logic  [7:0] ext_pfd_offset_rep[1:0]; 
    logic   en_ext_max_sel_mux; 
    logic  [4:0] ext_max_sel_mux[3:0]; 
    logic   en_pfd_cal; 
    logic   en_pfd_cal_rep; 
    logic  [3:0] Navg_adc; 
    logic  [3:0] Nbin_adc; 
    logic  [3:0] DZ_hist_adc; 
    logic  [3:0] Navg_adc_rep; 
    logic  [3:0] Nbin_adc_rep; 
    logic  [3:0] DZ_hist_adc_rep; 
    logic signed [7:0] adcout_avg[15:0]; 
    logic signed [23:0] adcout_sum[15:0]; 
    logic  [15:0] adcout_hist_center[15:0]; 
    logic  [15:0] adcout_hist_side[15:0]; 
    logic signed [7:0] pfd_offset[15:0]; 
    logic signed [7:0] adcout_avg_rep[1:0]; 
    logic signed [23:0] adcout_sum_rep[1:0]; 
    logic  [15:0] adcout_hist_center_rep[1:0]; 
    logic  [15:0] adcout_hist_side_rep[1:0]; 
    logic signed [7:0] pfd_offset_rep[1:0]; 
    logic  [3:0] Ndiv_clk_avg; 
    logic  [3:0] Ndiv_clk_cdr; 
    logic   int_rstb; 
    logic   sram_rstb; 
    logic   cdr_rstb; 
    logic  [3:0] sel_outbuff; 
    logic  [3:0] sel_trigbuff; 
    logic   en_outbuff; 
    logic   en_trigbuff; 
    logic  [2:0] Ndiv_outbuff; 
    logic  [2:0] Ndiv_trigbuff; 
    logic   bypass_out; 
    logic   bypass_trig; 
    logic  [9:0] in_addr; 
    logic signed [7:0] out_data[17:0]; 
    logic  [9:0] addr; 
    logic   tck; 
    logic   trst_n; 
    logic   tms; 
    logic   tdi; 
    logic   tdo; 
    logic   tdo_en; 
   

   modport des(
    output				en_v2t,
    output				en_slice,
    output				ctl_v2tn,
    output				ctl_v2tp,
    output				init,
    output				ALWS_ON,
    output				sel_pm_sign,
    output				sel_pm_in,
    output				sel_clk_TDC,
    output				en_pm,
    output				en_v2t_clk_next,
    output				en_sw_test,
    output				ctl_dcdl_late,
    output				ctl_dcdl_early,
    output				ctl_dcdl_TDC,
    output				en_gf,
    output				en_arb_pi,
    output				en_delay_pi,
    output				en_ext_Qperi,
    output				en_pm_pi,
    output				en_cal_pi,
    output				ext_Qperi,
    output				sel_pm_sign_pi,
    output				del_inc,
    output				ctl_dcdl_slice,
    output				ctl_dcdl_sw,
    output				disable_state,
    output				en_clk_sw,
    output				en_meas_pi,
    output				sel_meas_pi,
    output				en_slice_rep,
    output				ctl_v2tn_rep,
    output				ctl_v2tp_rep,
    output				init_rep,
    output				ALWS_ON_rep,
    output				sel_pm_sign_rep,
    output				sel_pm_in_rep,
    output				sel_clk_TDC_rep,
    output				en_pm_rep,
    output				en_v2t_clk_next_rep,
    output				en_sw_test_rep,
    output				ctl_dcdl_late_rep,
    output				ctl_dcdl_early_rep,
    output				ctl_dcdl_TDC_rep,
    output				sel_pfd_in,
    output				sel_pfd_in_meas,
    output				en_pfd_inp_meas,
    output				en_pfd_inn_meas,
    output				sel_del_out,
    output				disable_ibuf_async,
    output				disable_ibuf_aux,
    output				disable_ibuf_test0,
    output				disable_ibuf_test1,
    output				en_inbuf,
    output				sel_inbuf_in,
    output				bypass_inbuf_div,
    output				inbuf_ndiv,
    output				en_inbuf_meas,
    output				en_biasgen,
    output				ctl_biasgen,
    output				sel_del_out_pi,
    output				en_del_out_pi,
    input				pm_out,
    input				pm_out_pi,
    input				cal_out_pi,
    input				Qperi,
    input				max_sel_mux,
    input				pm_out_rep,
    output				pd_offset_ext,
    output				i_val,
    output				p_val,
    output				en_ext_pi_ctl_cdr,
    output				ext_pi_ctl_cdr,
    output				ext_pi_ctl_offset,
    output				en_ext_pfd_offset,
    output				ext_pfd_offset,
    output				en_ext_pfd_offset_rep,
    output				ext_pfd_offset_rep,
    output				en_ext_max_sel_mux,
    output				ext_max_sel_mux,
    output				en_pfd_cal,
    output				en_pfd_cal_rep,
    output				Navg_adc,
    output				Nbin_adc,
    output				DZ_hist_adc,
    output				Navg_adc_rep,
    output				Nbin_adc_rep,
    output				DZ_hist_adc_rep,
    input				adcout_avg,
    input				adcout_sum,
    input				adcout_hist_center,
    input				adcout_hist_side,
    input				pfd_offset,
    input				adcout_avg_rep,
    input				adcout_sum_rep,
    input				adcout_hist_center_rep,
    input				adcout_hist_side_rep,
    input				pfd_offset_rep,
    output				Ndiv_clk_avg,
    output				Ndiv_clk_cdr,
    output				int_rstb,
    output				sram_rstb,
    output				cdr_rstb,
    output				sel_outbuff,
    output				sel_trigbuff,
    output				en_outbuff,
    output				en_trigbuff,
    output				Ndiv_outbuff,
    output				Ndiv_trigbuff,
    output				bypass_out,
    output				bypass_trig,
    output				in_addr,
    input				out_data,
    input				addr,
    input				tck,
    input				trst_n,
    input				tms,
    input				tdi,
    output				tdo,
    output				tdo_en,
	       
   input Clk,
   input Reset
	       );
    
   
   // define testing modport
   modport test 
     (
      input				en_v2t,
      input				en_slice,
      input				ctl_v2tn,
      input				ctl_v2tp,
      input				init,
      input				ALWS_ON,
      input				sel_pm_sign,
      input				sel_pm_in,
      input				sel_clk_TDC,
      input				en_pm,
      input				en_v2t_clk_next,
      input				en_sw_test,
      input				ctl_dcdl_late,
      input				ctl_dcdl_early,
      input				ctl_dcdl_TDC,
      input				en_gf,
      input				en_arb_pi,
      input				en_delay_pi,
      input				en_ext_Qperi,
      input				en_pm_pi,
      input				en_cal_pi,
      input				ext_Qperi,
      input				sel_pm_sign_pi,
      input				del_inc,
      input				ctl_dcdl_slice,
      input				ctl_dcdl_sw,
      input				disable_state,
      input				en_clk_sw,
      input				en_meas_pi,
      input				sel_meas_pi,
      input				en_slice_rep,
      input				ctl_v2tn_rep,
      input				ctl_v2tp_rep,
      input				init_rep,
      input				ALWS_ON_rep,
      input				sel_pm_sign_rep,
      input				sel_pm_in_rep,
      input				sel_clk_TDC_rep,
      input				en_pm_rep,
      input				en_v2t_clk_next_rep,
      input				en_sw_test_rep,
      input				ctl_dcdl_late_rep,
      input				ctl_dcdl_early_rep,
      input				ctl_dcdl_TDC_rep,
      input				sel_pfd_in,
      input				sel_pfd_in_meas,
      input				en_pfd_inp_meas,
      input				en_pfd_inn_meas,
      input				sel_del_out,
      input				disable_ibuf_async,
      input				disable_ibuf_aux,
      input				disable_ibuf_test0,
      input				disable_ibuf_test1,
      input				en_inbuf,
      input				sel_inbuf_in,
      input				bypass_inbuf_div,
      input				inbuf_ndiv,
      input				en_inbuf_meas,
      input				en_biasgen,
      input				ctl_biasgen,
      input				sel_del_out_pi,
      input				en_del_out_pi,
      output				pm_out,
      output				pm_out_pi,
      output				cal_out_pi,
      output				Qperi,
      output				max_sel_mux,
      output				pm_out_rep,
      input				pd_offset_ext,
      input				i_val,
      input				p_val,
      input				en_ext_pi_ctl_cdr,
      input				ext_pi_ctl_cdr,
      input				ext_pi_ctl_offset,
      input				en_ext_pfd_offset,
      input				ext_pfd_offset,
      input				en_ext_pfd_offset_rep,
      input				ext_pfd_offset_rep,
      input				en_ext_max_sel_mux,
      input				ext_max_sel_mux,
      input				en_pfd_cal,
      input				en_pfd_cal_rep,
      input				Navg_adc,
      input				Nbin_adc,
      input				DZ_hist_adc,
      input				Navg_adc_rep,
      input				Nbin_adc_rep,
      input				DZ_hist_adc_rep,
      output				adcout_avg,
      output				adcout_sum,
      output				adcout_hist_center,
      output				adcout_hist_side,
      output				pfd_offset,
      output				adcout_avg_rep,
      output				adcout_sum_rep,
      output				adcout_hist_center_rep,
      output				adcout_hist_side_rep,
      output				pfd_offset_rep,
      input				Ndiv_clk_avg,
      input				Ndiv_clk_cdr,
      input				int_rstb,
      input				sram_rstb,
      input				cdr_rstb,
      input				sel_outbuff,
      input				sel_trigbuff,
      input				en_outbuff,
      input				en_trigbuff,
      input				Ndiv_outbuff,
      input				Ndiv_trigbuff,
      input				bypass_out,
      input				bypass_trig,
      input				in_addr,
      output				out_data,
      output				addr,
      output				tck,
      output				trst_n,
      output				tms,
      output				tdi,
      input				tdo,
      input				tdo_en,
    input Clk,
    input Reset
      );
   
      
    endinterface: raw_jtag_ifc_unq1
