# Adapted from Garnet and ButterPHY

name: qtm

commands:
  - |
    mkdir -p build
    mkdir -p outputs
    cd build

    # build input_buffer QTM
    mkdir -p input_buffer
    cd input_buffer
    pt_shell -f ../../input_buffer.qtm.tcl
    cd ..

    # build output_buffer QTM
    mkdir -p output_buffer
    cd output_buffer
    pt_shell -f ../../output_buffer.qtm.tcl
    cd ..

    # link build products into output folder
    cd ../outputs
    ln -s ../build/input_buffer/input_buffer_lib.db input_buffer_lib.db
    ln -s ../build/input_buffer/input_buffer.lib input_buffer.lib
    ln -s ../build/output_buffer/output_buffer_lib.db output_buffer_lib.db
    ln -s ../build/output_buffer/output_buffer.lib output_buffer.lib

outputs:
  - input_buffer_lib.db
  - input_buffer.lib
  - output_buffer_lib.db
  - output_buffer.lib