# Adapted from Garnet

name: qtm

commands:
  - mkdir -p build
  - mkdir -p outputs
  - cd build && pt_shell -f ../output_buffer.qtm.tcl
  - cd build && dc_shell-xg-t -f ../run_dc.tcl

outputs:
  - output_buffer.db
