# Adapted from Garnet and ButterPHY

name: qtm

commands:
  - |
    mkdir -p build
    mkdir -p outputs
    cd build

    mkdir -p output_buffer
    cd output_buffer
    pt_shell -f ../../output_buffer.qtm.tcl
    cp output_buffer_lib.db ../../outputs/.
    cd ..

outputs:
  - output_buffer_lib.db
