# Adapted from Garnet and ButterPHY

name: qtm

commands:
  - |
    mkdir -p build
    mkdir -p outputs
    cd build

    mkdir -p analog_core
    cd analog_core
    pt_shell -f ../../analog_core.qtm.tcl
    cp analog_core_lib.db ../../outputs/.
    cd ..

    mkdir -p input_buffer
    cd input_buffer
    pt_shell -f ../../input_buffer.qtm.tcl
    cp input_buffer_lib.db ../../outputs/.
    cd ..

    mkdir -p output_buffer
    cd output_buffer
    pt_shell -f ../../output_buffer.qtm.tcl
    cp output_buffer_lib.db ../../outputs/.
    cd ..

outputs:
  - analog_core_lib.db
  - input_buffer_lib.db
  - output_buffer_lib.db
