#=========================================================================
# Custom Scripts -- power
#=========================================================================

name: custom-power

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
  - globalnetconnect.default.tcl
  - power-strategy-dualmesh.default.tcl

