parameter_list:
  - &channel_width 16
  - &code_precision 8
  - &output_precision 10
  - &ffe_length 10
  - &ffe_weight_precision 10
  - &estimate_depth 30
  - &est_channel_precision 8
  - &est_code_precision 8
  - &est_error_precision 8
  - &sequence_length 3
  - &channel_shift_precision 4
  - &ffe_shift_precision 5


generate:
  channel:
    class: "PulseChannel"
    type: "dielectric1"
    file_name: "impulse_response.txt"
    parameters:
      baud_rate: 1
      sampling_pos: 0
      channel_depth: 125
      tau: 0.0087
      sample_rate: 100
      baud_rate: 1
      cursor_pos: *mlsd_est_cursor_pos


generic:
  parameters:
    channel_width: *channel_width
    code_precision : *code_precision
    ffe_length: *ffe_length
    ffe_weight_precision: *ffe_weight_precision
    ffe_shift: 8
    mlsd_shift: 8
  ffe:
    parameters:
      length : *ffe_length
      width  : *channel_width
      input_precision : *code_precision
      output_precision: *output_precision
      weight_precision: *ffe_weight_precision
      shift_precision: *ffe_shift_precision
    adaptation:
      type: 'wiener'
      args: { mu : 0.1 }
  comp:
    parameters:
      width : *channel_width
      input_precision : *output_precision
      conf_precision  : 8
      thresh_precision : *output_precision
    threshold:
      value: 0
  channel:
    parameters:
      width: *channel_width
      est_channel_depth: *estimate_depth
      est_channel_precision: *est_channel_precision
      est_code_precision: *est_code_precision
      shift_precision: *channel_shift_precision
  error:
    parameters:
      width: *channel_width
      est_error_precision: *est_error_precision
  detector:
    parameters:
      width: *channel_width
      seq_length: *sequence_length
      est_error_precision : *est_error_precision
      est_channel_precision: *est_channel_precision



