parameter_list:
  - &channel_width 16
  - &code_precision 8
  - &output_precision 9
  - &ffe_length 5
  - &ffe_weight_precision 11

generic:
  parameters:
    channel_width: *channel_width
    code_precision : *code_precision
    ffe_length: *ffe_length
    ffe_weight_precision: *ffe_weight_precision
  ffe:
    parameters:
      length : *ffe_length
      width  : *channel_width
      input_precision : *code_precision
      output_precision: *output_precision
      weight_precision: *ffe_weight_precision
      shift_precision: 10
    adaptation:
      type: 'wiener'
      args: { mu : 0.1 }
  comp:
    parameters:
      width : *channel_width
      input_precision : *output_precision
      conf_precision  : 4
      thresh_precision : *output_precision
    threshold:
      value: 0

