#=========================================================================
# Custom Scripts -- init
#=========================================================================

name: custom-route

#-------------------------------------------------------------------------
# Inputs and Outputs
#-------------------------------------------------------------------------

outputs:
- route-settings.tcl

parameters:
  num_mem_tiles: 4
