# Adapted from Garnet and ButterPHY

name: mdll_r1

commands:
  - |
    mkdir -p outputs
    tar -xzvf /home/sjkim85/dragonphy_tarballs/mdll_r1_top-latest.tar.gz -C outputs

outputs:
  - mdll_r1.lef
  - mdll_r1.gds
  - mdll_r1.lvs.v
  - mdll_r1.version
