# Adapted from Garnet and ButterPHY

name: output_buffer

commands:
  - |
    mkdir -p outputs
    tar -xzvf /home/sjkim85/dragonphy_tarballs/output_buffer-latest.tar.gz -C outputs

outputs:
  - output_buffer.lef
  - output_buffer.gds
  - output_buffer.lvs.v
  - output_buffer.version
