# Adapted from Garnet

name: openram-gen-sram

commands:
  - |
    # Option 1 (slow): Run OpenRAM to generate a *.lib file
    # python gen_config.py
    # python $OPENRAM_HOME/openram.py myconfig

    # Option 2 (fast): Copy over a pre-compiled *.lib file
    # Note that if the memory size changes the file will
    # have to be recompiled.
    mkdir -p temp
    cp lib.openram temp/sram_144_1024_freepdk45_TT_1p0V_25C.lib

    # run script to generate a *.db file from the *.lib model
    dc_shell-xg-t -f generate_db.tcl

parameters:
  sram_word_size: 144
  sram_num_words: 1024
  sram_tech_name: freepdk45
  sram_output_path: temp

outputs:
  - sram_tt.db
