# Adapted from Garnet

name: openram-gen-sram

commands:
  - |
    python gen_config.py
    python $OPENRAM_HOME/openram.py myconfig
    dc_shell-xg-t -f generate_db.tcl

parameters:
  sram_word_size: 144
  sram_num_words: 1024
  sram_tech_name: freepdk45
  sram_output_path: temp

outputs:
  - sram_tt.db
