
test1:
    gain:
    - coef:
        thm_sel_bld[0]: 0.0625
        thm_sel_bld[1]: 0.0625
        thm_sel_bld[2]: 0.0625
        thm_sel_bld[3]: 0.0625
        thm_sel_bld[4]: 0.0625
        thm_sel_bld[5]: 0.0625
        thm_sel_bld[6]: 0.0625
        thm_sel_bld[7]: 0.0625
        thm_sel_bld[8]: 0.0625
        thm_sel_bld[9]: 0.0625
        thm_sel_bld[10]: 0.0625
        thm_sel_bld[11]: 0.0625
        thm_sel_bld[12]: 0.0625
        thm_sel_bld[13]: 0.0625
        thm_sel_bld[14]: 0.0625
        thm_sel_bld[15]: 0.0625
      mode:
        dummy_digitalmode: 0
    offset:
    - coef:
        (1.0): 0.2
      mode:
        dummy_digitalmode: 0

